{
 "title": "Basic HPWC Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Grid Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_hz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_hz" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_hz" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Session Wh",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "session_energy_wh" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Session Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "session_energy_wh" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000*0.24" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_v" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "grid_v" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vehicle Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "query": "SELECT mean(\"vehicle_current_a\")*mean(\"grid_v\") FROM \"hpwc\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "vehicle_current_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "MCU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "query": "SELECT mean(\"mcu_temp_c\")*(9/5)+32 FROM \"hpwc\" WHERE $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "mcu_temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Handle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "query": "SELECT mean(\"handle_temp_c\")*(9/5)+32 FROM \"hpwc\" WHERE $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "handle_temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "PCB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "query": "SELECT mean(\"pcba_temp_c\")*(9/5)+32 FROM \"hpwc\" WHERE $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "pcba_temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vehicle Amps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "The Spaceship",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpwc",
     "select": [
      [
       { "params": [ "vehicle_current_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}