version: "3.7" # todo(averysmalldog): let's see if there's a better version to pin
services:
  grafana:
    image: grafana/grafana # todo(averysmalldog): lock to a version
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes: # todo(averysmalldog): yeah, this volume is definitely not used. Need to fix that.
      - grafana-volume:/vol01/Docker/monitoring
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes: # todo(averysmalldog): same as above, this volume is definitely not used. Need to fix that.
      - influxdb-volume:/var/lib/influxdb
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=tesla
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
  polly:
    image: averysmalldog/tesla-gen3wc-monitor # todo(averysmalldog): make it so this can be built locally (less dependent on docker hub)
    container_name: polly
    restart: always
    networks:
      - monitoring
    environment: 
      - HPWC_IP
      - INFLUX_IP=host.docker.internal
    depends_on:
      - influxdb
networks:
  monitoring:
volumes: # todo(averysmalldog): I think this is where some tweaks have to be made, maybe
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
