services:
  grafana:
    image: grafana/grafana # todo(averysmalldog): lock to a version
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2      
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=tesla
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
  tesla-gen3wc-monitor:
    image: averysmalldog/tesla-gen3wc-monitor
    container_name: tesla-gen3wc-monitor
    restart: always
    networks:
      - monitoring
    environment: 
      - HPWC_IP
      - INFLUX_IP=host.docker.internal
    depends_on:
      - influxdb
networks:
  monitoring:
volumes: # todo(averysmalldog): I think this is where some tweaks have to be made, maybe
  grafana_data:
    external: true
  grafana_config:
    external: true
  influxdb_data:
    external: true
  influxdb_config:
    external: true
